### ISSUE TITLE
proceso de negocio

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-buscadores-de-datos#1]
[Procesos de negocios.pdf](https://github.com/user-attachments/files/17122106/Procesos.de.negocios.pdf)

*Roldan Uriel Arcadio Avila 
*Ariadna Monserrat Lopez Aparicio

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by evelyn-santiago** [comment]
19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
